color0 #131313
color1 #ffb4ab
color2 #ffb0cc
color3 #e2bdc8
color4 #f0bc95
color5 #ffb0cc
color6 #e2bdc8
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #ffb0cc
color11 #e2bdc8
color12 #f0bc95
color13 #ffb0cc
color14 #e2bdc8
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #ffb0cc
inactive_border_color #474747
url_color             #ffb0cc

active_tab_foreground   #5d1137
active_tab_background   #ffb0cc
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
