[colors.primary]
background = '#0b151a'
foreground = '#dae4ec'
 
[colors.cursor]
text = '#dae4ec'
cursor = '#b5c9d7' 
 
[colors.vi_mode_cursor]
text = '#0b151a'
cursor = '#54dbc8' 
 
[colors.search.matches]
foreground = '#374955' 
background = '#8fcef3' 
 
[colors.search.focused_match]
foreground = '#374955' 
background = '#54dbc8' 
 
[colors.footer_bar]
foreground = '#374955' 
background = '#dae4ec' 
 
[colors.hints.start]
foreground = '#374955' 
background = '#82d5c7' 
 
[colors.hints.end]
foreground = '#374955' 
background = '#82d5c7' 
 
[colors.selection]
text = '#0b151a'
background = '#54dbc8'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#54dbc8' 
yellow = '#006b60' 
blue = '#54dbc8' 
magenta = '#8fcef3' 
cyan = '#82d5c7' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 