# Colors (Noctalia)

[colors.bright]
black = '#161b22'
blue = '#fb776f'
cyan = '#cba5ff'
green = '#6bf28d'
magenta = '#cba5ff'
red = '#ff6c65'
white = '#ffffff'
yellow = '#f2e76b'

[colors.cursor]
cursor = '#d55149'
text = '#010409'

[colors.normal]
black = '#010409'
blue = '#d55149'
cyan = '#bc8cff'
green = '#46cc67'
magenta = '#bc8cff'
red = '#f85149'
white = '#c9d1d9'
yellow = '#ccc146'

[colors.primary]
background = '#010409'
foreground = '#c9d1d9'

[colors.selection]
background = '#d55149'
text = '#010409'
