color0 #131313
color1 #ffb4ab
color2 #ffb68c
color3 #e5bfaa
color4 #ccc991
color5 #ffb68c
color6 #e5bfaa
color7 #e2e2e2
color8 #919191
color9 #ffb4ab
color10 #ffb68c
color11 #e5bfaa
color12 #ccc991
color13 #ffb68c
color14 #e5bfaa
color15 #e2e2e2

cursor                #e2e2e2
cursor_text_color     #131313
background            #131313
foreground            #e2e2e2
selection_foreground  #c6c6c6
selection_background  #474747
active_border_color   #ffb68c
inactive_border_color #474747
url_color             #ffb68c

active_tab_foreground   #532200
active_tab_background   #ffb68c
inactive_tab_foreground #c6c6c6
inactive_tab_background #474747
cursor_trail_color      #c6c6c6
