color0 #010409
color1 #f85149
color2 #46cc67
color3 #ccc146
color4 #d55149
color5 #bc8cff
color6 #bc8cff
color7 #c9d1d9
color8 #161b22
color9 #ff6c65
color10 #6bf28d
color11 #f2e76b
color12 #fb776f
color13 #cba5ff
color14 #cba5ff
color15 #ffffff
background #010409
selection_foreground #010409
cursor #d55149
cursor_text_color #010409
foreground #c9d1d9
selection_background #d55149
active_border_color #d55149
inactive_border_color #bc8cff

active_tab_foreground   #010409
active_tab_background   #d55149
inactive_tab_foreground #8b949e
inactive_tab_background #161b22
cursor_trail_color      #8b949e
