color0 #1e100c
color1 #ffb4ab
color2 #ffaedf
color3 #f9b1dc
color4 #ffb5a0
color5 #ffaedf
color6 #f9b1dc
color7 #f9dcd5
color8 #ae887e
color9 #ffb4ab
color10 #ffaedf
color11 #f9b1dc
color12 #ffb5a0
color13 #ffaedf
color14 #f9b1dc
color15 #f9dcd5

cursor                #f9dcd5
cursor_text_color     #1e100c
background            #1e100c
foreground            #f9dcd5
selection_foreground  #e7bdb2
selection_background  #5d4037
active_border_color   #ffaedf
inactive_border_color #5d4037
url_color             #ffaedf

active_tab_foreground   #591147
active_tab_background   #ffaedf
inactive_tab_foreground #e7bdb2
inactive_tab_background #5d4037
cursor_trail_color      #e7bdb2
