# ~/.config/starship.toml

format = """
[╭──](blue)\
[\\(](blue)\
$username\
[㉿](red)\
$hostname\
[\\)─](blue)\
$time\
[-](blue)\
$directory\
$cmd_duration\
$all\
$line_break\
[╰─](blue)\
$character\
"""

[username]
format = "[$user](bold red)"
show_always = true

[hostname]
format = "[$hostname](bold red)"
ssh_only = false
disabled = false

[directory]
format = "[\\[](blue)[$path](bold cyan)[\\]](blue)"
truncation_length = 3
truncate_to_repo = false

[time]
format = "[\\(](blue)[$time](bold yellow)[\\)](blue)"
time_format = "%Y/%m/%d)(%H:%M:%S"
disabled = false

[cmd_duration]
format = '[\[$duration\]]($style)'
style = "bold blue"
min_time = 1000

[character]
success_symbol = "[❯❯](bold purple)"
error_symbol = "[x❯](bold red)"

[python]
format = '\[[🐍 $version (\($virtualenv\))]($style)\]'
style = 'bold #eaff64'

[rust]
format = '\[[🦀 $version]($style)\]'
style = 'bold #dea584'

[git_branch]
format = ' \[[$symbol$branch]($style) '
symbol = ' '
style = 'bold purple'

[git_status]
format = '[$all_status$ahead_behind]($style)\]'
style = 'bold purple'
conflicted = '🏳 '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇕ '
untracked = ' '
stashed = '📦 '
modified = ' '
staged = '✓ '
renamed = '⇢ '
deleted = '✘ '

[package]
disabled = true
[line_break]
disabled = false
